name: Tests

on:
  push:
    branches: [ docu ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        extra: ['', 'xformers_attention']
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pip setuptools wheel
        pip install -r requirements.txt
        pip install pytest
        pip install git+https://github.com/pygae/clifford  # for equivariance tests

        if [[ -z "${{ matrix.extra }}" ]]; then
          pip install -e .
        else
          pip install -e ".[${{ matrix.extra }}]"
        fi    

    - name: Run unit tests
      run: |
        pytest tests/lgatr
